### ISSUE TITLE
Image upload support

### ISSUE THREAD

**Issue by frankleng** [arikchakma/maily.to#41]
any plan to implement upload?
happy to contribute if u can give some pointers. thanks and great work!

PS. I'd add signed S3 upload + auto fill final url to image block

**Comment by arikchakma** [comment]
I do have plans to do it. For the package, I will expose an API something like `onImageUpload` or `onImageDrop`, and let the user do whatever they want. But for the app, I need to think differently because image upload requires some amount of money. So let's see, I'm closing it for now and will be back with a solution.
